#!/usr/bin/env bash

### Study Tracker dependencies
export ST_VERSION="0.9.3"
#export ST_VERSION="latest"

### Study Tracker user configuration
# This is is used to create an admin user account in Study Tracker on initialization.
# Required
export ADMIN_EMAIL="person@email.com"
export ADMIN_PASSWORD="thisismypassword"

### Benchling
# Enables integration with Benchling. Provide your tenant name (for example, if your Benchling URL is
# https://myorg.benchling.com then your tenant name will be 'myorg'. The Client ID and secret can be
# acquired by registering a new 'App' in your tenant.
# Optional
export BENCHLING_TENANT_NAME="example"
export BENCHLING_CLIENT_ID="xxxxxx"
export BENCHLING_CLIENT_SECRET="xxxxxx"

### AWS Environment
# Provide the VPC ID, account #, and region for your deployment. Provide subnet IDs for your EC2 and
# RDS service deployments. These should be private subnets.
# Required
export VPC_ID="vpc-xxxxx"
export AWS_ACCOUNT_ID="1234567890"
export AWS_REGION="us-east-1"
export SUBNET_IDS="subnet-xxxxxxx:us-east-1a,subnet-xxxxxxx:us-east-1b"

### EC2
# Provide the name of the existing key pair that will be used to grant SSH access to your EC2 instance
# Required
export EC2_SSH_KEY_NAME="MY_KEY"

# If you'd like to attach any additional security groups to your EC2 instance, provide their IDs here.
# Optional
export EC2_SECURITY_GROUP_IDS="sg-xxxxxxx,sg-xxxxxxx"

### Elasticsearch
# Provide the subnet ID to be used to deploy your Elasticsearch instance
# Required
export ES_SUBNET_ID="subnet-xxxxxxxx"

### S3
# Provide the name of the S3 bucket that will be used to store Study Tracker data. If not provided,
# a new bucket will be created with a generic name.
# Optional
export S3_BUCKET_NAME="my-study-tracker-bucket"

### Email
# Provide SMTP connection information so that Study Tracker can send account activation emails to users.
# Required
export SMTP_HOST="smtp.office365.com"
export SMTP_PORT="587"
export SMTP_USER="username@myorg.onmicrosoft.com"
export SMTP_PASSWORD="xxxxxxx"
